laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('empresa', 'EmpresaController@index')->name('empresa');

    Route::get('produtos/{produtos_categoria?}', 'ProdutosController@index')->name('produtos');
    Route::get('produtos/{produtos_categoria}/{produto_slug}', 'ProdutosController@show')->name('produtos.show');
    Route::post('adiciona-produto', 'OrcamentoController@adiciona');
    Route::post('exclui-produto', 'OrcamentoController@exclui');
    Route::post('atualiza-produto', 'OrcamentoController@atualiza');

    Route::get('noticias/{noticia_slug?}', 'NoticiasController@index')->name('noticias');
    Route::get('promocoes', 'PromocoesController@index')->name('promocoes');

    Route::get('representantes', 'RepresentantesController@index')->name('representantes');
    Route::post('representantes', 'RepresentantesController@post')->name('representantes.post');

    Route::get('faq', 'FaqController@index')->name('faq');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::get('busca', 'ProdutosController@busca')->name('busca');

    Route::post('orcamento/cadastro', 'OrcamentoController@cadastro')->name('orcamento.cadastro');
    Route::post('orcamento/redefinir', 'Auth\PasswordController@sendResetLinkEmail')->name('orcamento.redefinir');
    Route::get('orcamento/redefinicao/{token}', 'Auth\PasswordController@showResetForm');
    Route::post('orcamento/reset', 'Auth\PasswordController@reset')->name('orcamento.reset');
    Route::post('orcamento/login', 'OrcamentoController@login')->name('orcamento.login');
    Route::get('orcamento/logout', 'OrcamentoController@logout')->name('orcamento.logout');
    Route::get('orcamento', 'OrcamentoController@index')->name('orcamento');

    Route::group(['middleware' => 'authCliente'], function() {
        Route::post('orcamento', 'OrcamentoController@post')->name('orcamento.post');
    });

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth', 'authAdmin']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
        Route::resource('produtos/categorias', 'ProdutosCategoriasController');
        Route::resource('produtos', 'ProdutosController');
        Route::get('produtos/{produtos}/imagens/clear', [
            'as'   => 'painel.produtos.imagens.clear',
            'uses' => 'ProdutosImagensController@clear'
        ]);
        Route::resource('produtos.imagens', 'ProdutosImagensController', ['parameters' => ['imagens' => 'imagens_produtos']]);
        Route::resource('representantes/contatos', 'RepresentantesContatosController');
		Route::resource('representantes', 'RepresentantesController');
		Route::resource('home/chamadas', 'ChamadasController', ['only' => ['index', 'update']]);
		Route::resource('home/banners', 'BannersController');
		Route::resource('empresa/certificacoes', 'EmpresaCertificacoesController');
		Route::resource('empresa', 'EmpresaController', ['only' => ['index', 'update']]);
        Route::resource('noticias', 'NoticiasController');
		Route::resource('faq/imagem', 'FaqImagemController', ['only' => ['index', 'update']]);
		Route::resource('faq', 'FaqController');
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('orcamentos', 'OrcamentosController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Models/Contato.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Contato extends Model
{
    protected $table = 'contato';

    protected $guarded = ['id'];
}

laravel/app/Models/Orcamento.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Orcamento extends Model
{
    protected $table = 'orcamentos';

    protected $guarded = ['id'];

    public function getCreatedAtAttribute($date)
    {
        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d/m/Y');
    }

    public function scopeNaoLidos($query)
    {
        return $query->where('lido', '!=', 1);
    }

    public function countNaoLidos()
    {
        return $this->naoLidos()->count();
    }

    public function cliente()
    {
        return $this->belongsTo('App\Models\User', 'user_id');
    }
}

laravel/app/Models/Representante.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Helpers\CropImage;

class Representante extends Model
{
    protected $table = 'representantes';

    protected $guarded = ['id'];

    public function scopeOrdenados($query)
    {
        return $query->orderBy('ordem', 'ASC')->orderBy('id', 'DESC');
    }

}

laravel/app/Http/Controllers/ContatoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests\ContatosRecebidosRequest;

use App\Models\Contato;
use App\Models\ContatoRecebido;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('frontend.contato', compact('contato'));
    }

    public function post(ContatosRecebidosRequest $request, ContatoRecebido $contatoRecebido)
    {
        $contatoRecebido->create($request->all());

        $contato = Contato::first();

        if (isset($contato->email)) {
            \Mail::send('emails.contato', $request->all(), function($message) use ($request, $contato)
            {
                $message->to($contato->email, config('site.name'))
                        ->subject('[CONTATO] '.config('site.name'))
                        ->replyTo($request->get('email'), $request->get('nome'));
            });
        }

        $response = [
            'status'  => 'success',
            'message' => 'Mensagem enviada com sucesso!'
        ];

        return response()->json($response);
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/RepresentantesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\RepresentantesRequest;
use App\Http\Controllers\Controller;

use App\Models\Representante;
use App\Models\ContatoRepresentante;

class RepresentantesController extends Controller
{
    public function index()
    {
        $registros = Representante::ordenados()->get();
        $contatosRepresentantesNaoLidos = ContatoRepresentante::naoLidos()->count();

        return view('painel.representantes.index', compact('registros', 'contatosRepresentantesNaoLidos'));
    }

    public function create()
    {
        return view('painel.representantes.create');
    }

    public function store(RepresentantesRequest $request)
    {
        try {

            $input = $request->all();


            Representante::create($input);
            return redirect()->route('painel.representantes.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Representante $registro)
    {
        return view('painel.representantes.edit', compact('registro'));
    }

    public function update(RepresentantesRequest $request, Representante $registro)
    {
        try {

            $input = $request->all();


            $registro->update($input);
            return redirect()->route('painel.representantes.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Representante $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.representantes.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/RepresentantesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests\ContatosRepresentantesRequest;

use App\Models\Contato;
use App\Models\Representante;
use App\Models\ContatoRepresentante;

class RepresentantesController extends Controller
{
    public function index()
    {
        $estadosCadastrados = Representante::orderBy('estado', 'ASC')->pluck('estado')->toArray();
        $estados = [];
        foreach ($estadosCadastrados as $uf) {
            $estados[$uf] = \Tools::listaEstados()[$uf];
        }

        if (request('uf')) {
            $uf      = request('uf');
            $cidade  = request('cidade');

            $cidades = Representante::where('estado', $uf)
                        ->orderBy('cidade', 'ASC')
                        ->pluck('cidade', 'cidade');

            $representantes = Representante::where('estado', $uf);

            if ($cidade) $representantes = $representantes->where('cidade', $cidade);

            $representantes = $representantes->ordenados()->get();

            return view('frontend.representantes.show', compact('estados', 'cidades', 'uf', 'cidade', 'representantes'));
        }

        return view('frontend.representantes.index', compact('estados'));
    }

    public function post(ContatosRepresentantesRequest $request, ContatoRepresentante $contatoRecebido)
    {
        $contatoRecebido->create($request->all());

        $contato = Contato::first();

        if (isset($contato->email)) {
            \Mail::send('emails.representante', $request->all(), function($message) use ($request, $contato)
            {
                $message->to($contato->email, config('site.name'))
                        ->subject('[REPRESENTANTE] '.config('site.name'))
                        ->replyTo($request->get('email'), $request->get('nome'));
            });
        }

        $response = [
            'status'  => 'success',
            'message' => 'Mensagem enviada com sucesso!'
        ];

        return response()->json($response);
    }
}

laravel/resources/views/painel/representantes/contatos/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <a href="{{ route('painel.representantes.index') }}" class="btn btn-sm btn-default">
        &larr; Voltar para Representantes
    </a>

    <legend>
        <h2><small>Representantes /</small> Contatos Recebidos</h2>
    </legend>

    @if(!count($contatosrecebidos))
    <div class="alert alert-warning" role="alert">Nenhuma mensagem recebida.</div>
    @else
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>Data</th>
                <th>Nome</th>
                <th>E-mail</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($contatosrecebidos as $contato)

            <tr class="tr-row @if(!$contato->lido) warning @endif">
                <td>{{ $contato->created_at }}</td>
                <td>{{ $contato->nome }}</td>
                <td>{{ $contato->email }}</td>
                <td class="crud-actions">
                    {!! Form::open([
                        'route'  => ['painel.representantes.contatos.destroy', $contato->id],
                        'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.representantes.contatos.show', $contato->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-align-left" style="margin-right:10px;"></span>Ler mensagem
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>

        @endforeach
        </tbody>
    </table>
    {!! $contatosrecebidos->render() !!}
    @endif

@stop

laravel/resources/views/painel/representantes/contatos/show.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Representantes /</small> Contatos Recebidos</h2>
    </legend>

    <div class="form-group">
        <label>Data</label>
        <div class="well">{{ $contato->created_at }}</div>
    </div>

    <div class="form-group">
        <label>Nome</label>
        <div class="well">{{ $contato->nome }}</div>
    </div>

    <div class="form-group">
        <label>E-mail</label>
        <div class="well">{{ $contato->email }}</div>
    </div>

@if($contato->telefone)
    <div class="form-group">
        <label>Telefone</label>
        <div class="well">{{ $contato->telefone }}</div>
    </div>
@endif

    <div class="form-group">
        <label>Cidade/UF</label>
        <div class="well">{{ $contato->cidade_uf }}</div>
    </div>

    <div class="form-group">
        <label>Mensagem</label>
        <div class="well">{{ $contato->mensagem }}</div>
    </div>

    <a href="{{ route('painel.representantes.contatos.index') }}" class="btn btn-default btn-voltar">Voltar</a>

@stop