laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('empresa', 'EmpresaController@index')->name('empresa');

    Route::get('produtos/{produtos_categoria?}', 'ProdutosController@index')->name('produtos');
    Route::get('produtos/{produtos_categoria}/{produto_slug}', 'ProdutosController@show')->name('produtos.show');
    Route::post('adiciona-produto', 'OrcamentoController@adiciona');
    Route::post('exclui-produto', 'OrcamentoController@exclui');
    Route::post('atualiza-produto', 'OrcamentoController@atualiza');

    Route::get('noticias/{noticia_slug?}', 'NoticiasController@index')->name('noticias');
    Route::get('promocoes', 'PromocoesController@index')->name('promocoes');

    Route::get('representantes', 'RepresentantesController@index')->name('representantes');
    Route::post('representantes', 'RepresentantesController@post')->name('representantes.post');

    Route::get('faq', 'FaqController@index')->name('faq');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::get('busca', 'ProdutosController@busca')->name('busca');

    Route::post('orcamento/cadastro', 'OrcamentoController@cadastro')->name('orcamento.cadastro');
    Route::post('orcamento/redefinir', 'Auth\PasswordController@sendResetLinkEmail')->name('orcamento.redefinir');
    Route::get('orcamento/redefinicao/{token}', 'Auth\PasswordController@showResetForm');
    Route::post('orcamento/reset', 'Auth\PasswordController@reset')->name('orcamento.reset');
    Route::post('orcamento/login', 'OrcamentoController@login')->name('orcamento.login');
    Route::get('orcamento/logout', 'OrcamentoController@logout')->name('orcamento.logout');
    Route::get('orcamento', 'OrcamentoController@index')->name('orcamento');

    Route::group(['middleware' => 'authCliente'], function() {
        Route::post('orcamento', 'OrcamentoController@post')->name('orcamento.post');
    });

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth', 'authAdmin']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
        Route::resource('produtos/categorias', 'ProdutosCategoriasController');
        Route::resource('produtos', 'ProdutosController');
        Route::get('produtos/{produtos}/imagens/clear', [
            'as'   => 'painel.produtos.imagens.clear',
            'uses' => 'ProdutosImagensController@clear'
        ]);
        Route::resource('produtos.imagens', 'ProdutosImagensController', ['parameters' => ['imagens' => 'imagens_produtos']]);
        Route::resource('representantes/contatos', 'RepresentantesContatosController');
		Route::resource('representantes', 'RepresentantesController');
		Route::resource('home/chamadas', 'ChamadasController', ['only' => ['index', 'update']]);
		Route::resource('home/banners', 'BannersController');
		Route::resource('empresa/certificacoes', 'EmpresaCertificacoesController');
		Route::resource('empresa', 'EmpresaController', ['only' => ['index', 'update']]);
        Route::resource('noticias', 'NoticiasController');
		Route::resource('faq/imagem', 'FaqImagemController', ['only' => ['index', 'update']]);
		Route::resource('faq', 'FaqController');
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('orcamentos', 'OrcamentosController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);
            return redirect()->route('painel.home.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $registro->update($input);
            return redirect()->route('painel.home.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.home.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ChamadasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ChamadasRequest;
use App\Http\Controllers\Controller;

use App\Models\Chamadas;

class ChamadasController extends Controller
{
    public function index()
    {
        $registro = Chamadas::first();

        return view('painel.chamadas.edit', compact('registro'));
    }

    public function update(ChamadasRequest $request, Chamadas $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['chamada_1_imagem'])) $input['chamada_1_imagem'] = Chamadas::upload_chamada_1_imagem();
            if (isset($input['chamada_2_imagem'])) $input['chamada_2_imagem'] = Chamadas::upload_chamada_2_imagem();
            if (isset($input['chamada_3_imagem'])) $input['chamada_3_imagem'] = Chamadas::upload_chamada_3_imagem();

            $registro->update($input);

            return redirect()->route('painel.home.chamadas.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('id', 'DESC')->paginate(15);

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/EmpresaCertificacoesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\EmpresaCertificacoesRequest;
use App\Http\Controllers\Controller;

use App\Models\Certificacao;

class EmpresaCertificacoesController extends Controller
{
    public function index()
    {
        $registros = Certificacao::ordenados()->get();

        return view('painel.empresa.certificacoes.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.empresa.certificacoes.create');
    }

    public function store(EmpresaCertificacoesRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Certificacao::upload_imagem();

            Certificacao::create($input);
            return redirect()->route('painel.empresa.certificacoes.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Certificacao $registro)
    {
        return view('painel.empresa.certificacoes.edit', compact('registro'));
    }

    public function update(EmpresaCertificacoesRequest $request, Certificacao $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Certificacao::upload_imagem();

            $registro->update($input);
            return redirect()->route('painel.empresa.certificacoes.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Certificacao $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.empresa.certificacoes.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/EmpresaController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\EmpresaRequest;
use App\Http\Controllers\Controller;

use App\Models\Empresa;

class EmpresaController extends Controller
{
    public function index()
    {
        $registro = Empresa::first();

        return view('painel.empresa.edit', compact('registro'));
    }

    public function update(EmpresaRequest $request, Empresa $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Empresa::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.empresa.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/FaqController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\FaqRequest;
use App\Http\Controllers\Controller;

use App\Models\Pergunta;

class FaqController extends Controller
{
    public function index()
    {
        $registros = Pergunta::ordenados()->get();

        return view('painel.faq.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.faq.create');
    }

    public function store(FaqRequest $request)
    {
        try {

            $input = $request->all();


            Pergunta::create($input);
            return redirect()->route('painel.faq.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Pergunta $registro)
    {
        return view('painel.faq.edit', compact('registro'));
    }

    public function update(FaqRequest $request, Pergunta $registro)
    {
        try {

            $input = $request->all();


            $registro->update($input);
            return redirect()->route('painel.faq.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Pergunta $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.faq.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/FaqImagemController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\FaqImagemRequest;
use App\Http\Controllers\Controller;

use App\Models\FaqImagem;

class FaqImagemController extends Controller
{
    public function index()
    {
        $registro = FaqImagem::first();

        return view('painel.faq.imagem.edit', compact('registro'));
    }

    public function update(FaqImagemRequest $request, FaqImagem $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = FaqImagem::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.faq.imagem.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/NoticiasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\NoticiasRequest;
use App\Http\Controllers\Controller;

use App\Models\Noticia;

class NoticiasController extends Controller
{
    public function index()
    {
        $registros = Noticia::ordenados()->paginate(10);

        return view('painel.noticias.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.noticias.create');
    }

    public function store(NoticiasRequest $request)
    {
        try {

            $input = $request->all();


            Noticia::create($input);
            return redirect()->route('painel.noticias.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Noticia $registro)
    {
        return view('painel.noticias.edit', compact('registro'));
    }

    public function update(NoticiasRequest $request, Noticia $registro)
    {
        try {

            $input = $request->all();


            $registro->update($input);
            return redirect()->route('painel.noticias.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Noticia $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.noticias.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">
    <li class="dropdown @if(str_is('painel.home*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Home
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(str_is('painel.home.banners*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.home.banners.index') }}">Banners</a>
            </li>
            <li @if(str_is('painel.home.chamadas*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.home.chamadas.index') }}">Chamadas</a>
            </li>
        </ul>
    </li>
    <li @if(str_is('painel.empresa*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.empresa.index') }}">Empresa</a>
    </li>
    <li @if(str_is('painel.produtos*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.produtos.index') }}">Produtos</a>
    </li>
    <li @if(str_is('painel.noticias*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.noticias.index') }}">Notícias</a>
    </li>
	<li @if(str_is('painel.representantes*', Route::currentRouteName())) class="active" @endif>
		<a href="{{ route('painel.representantes.index') }}">
            Representantes
            @if($contatosRepresentantesNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosRepresentantesNaoLidos }}</span>
            @endif
        </a>
    </li>
	<li @if(str_is('painel.faq*', Route::currentRouteName())) class="active" @endif>
		<a href="{{ route('painel.faq.index') }}">FAQ</a>
	</li>
    <li class="dropdown @if(str_is('painel.contato*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contato
            @if($contatosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{{ route('painel.contato.index') }}">Informações de Contato</a></li>
            <li><a href="{{ route('painel.contato.recebidos.index') }}">
                Contatos Recebidos
                @if($contatosNaoLidos >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                @endif
            </a></li>
        </ul>
    </li>
    <li @if(str_is('painel.orcamentos*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.orcamentos.index') }}">
            Orçamentos
            @if($orcamentosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $orcamentosNaoLidos }}</span>
            @endif
        </a>
    </li>
</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ config('site.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/vendor/bootswatch-dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/jquery-ui/themes/cupertino/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/painel/painel.css') }}">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url('/') }}">{{ config('site.name') }}</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                @include('painel.common.nav')

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown @if(str_is('painel.usuarios*', Route::currentRouteName())) active @endif">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                            Sistema <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ route('painel.usuarios.index') }}">Usuários</a></li>
                            <li><a href="{{ route('logout') }}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{{ asset("assets/vendor/jquery/dist/jquery.min.js") }}"><\/script>')</script>
    <script src="{{ asset('assets/vendor/bootswatch-dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/jquery-ui/jquery-ui.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/bootbox.js/bootbox.js') }}"></script>
    <script src="{{ asset('assets/vendor/jquery.inputmask/dist/min/jquery.inputmask.bundle.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/vendor/blueimp-file-upload/js/jquery.fileupload.js') }}"></script>
    <script src="{{ asset('assets/painel/painel.js') }}"></script>
</body>
</html>