laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('empresa', 'EmpresaController@index')->name('empresa');

    Route::get('produtos/{produtos_categoria?}', 'ProdutosController@index')->name('produtos');
    Route::get('produtos/{produtos_categoria}/{produto_slug}', 'ProdutosController@show')->name('produtos.show');
    Route::post('adiciona-produto', 'OrcamentoController@adiciona');
    Route::post('exclui-produto', 'OrcamentoController@exclui');
    Route::post('atualiza-produto', 'OrcamentoController@atualiza');

    Route::get('noticias/{noticia_slug?}', 'NoticiasController@index')->name('noticias');
    Route::get('promocoes', 'PromocoesController@index')->name('promocoes');

    Route::get('representantes', 'RepresentantesController@index')->name('representantes');
    Route::post('representantes', 'RepresentantesController@post')->name('representantes.post');

    Route::get('faq', 'FaqController@index')->name('faq');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::get('busca', 'ProdutosController@busca')->name('busca');

    Route::post('orcamento/cadastro', 'OrcamentoController@cadastro')->name('orcamento.cadastro');
    Route::post('orcamento/redefinir', 'Auth\PasswordController@sendResetLinkEmail')->name('orcamento.redefinir');
    Route::get('orcamento/redefinicao/{token}', 'Auth\PasswordController@showResetForm');
    Route::post('orcamento/reset', 'Auth\PasswordController@reset')->name('orcamento.reset');
    Route::post('orcamento/login', 'OrcamentoController@login')->name('orcamento.login');
    Route::get('orcamento/logout', 'OrcamentoController@logout')->name('orcamento.logout');
    Route::get('orcamento', 'OrcamentoController@index')->name('orcamento');

    Route::group(['middleware' => 'authCliente'], function() {
        Route::post('orcamento', 'OrcamentoController@post')->name('orcamento.post');
    });

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth', 'authAdmin']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
        Route::resource('produtos/categorias', 'ProdutosCategoriasController');
        Route::resource('produtos', 'ProdutosController');
        Route::get('produtos/{produtos}/imagens/clear', [
            'as'   => 'painel.produtos.imagens.clear',
            'uses' => 'ProdutosImagensController@clear'
        ]);
        Route::resource('produtos.imagens', 'ProdutosImagensController', ['parameters' => ['imagens' => 'imagens_produtos']]);
        Route::resource('representantes/contatos', 'RepresentantesContatosController');
		Route::resource('representantes', 'RepresentantesController');
		Route::resource('home/chamadas', 'ChamadasController', ['only' => ['index', 'update']]);
		Route::resource('home/banners', 'BannersController');
		Route::resource('empresa/certificacoes', 'EmpresaCertificacoesController');
		Route::resource('empresa', 'EmpresaController', ['only' => ['index', 'update']]);
        Route::resource('noticias', 'NoticiasController');
		Route::resource('faq/imagem', 'FaqImagemController', ['only' => ['index', 'update']]);
		Route::resource('faq', 'FaqController');
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('orcamentos', 'OrcamentosController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Models/Empresa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Helpers\CropImage;

class Empresa extends Model
{
    protected $table = 'empresa';

    protected $guarded = ['id'];

    public static function upload_imagem()
    {
        return CropImage::make('imagem', [
            'width'  => 600,
            'height' => null,
            'path'   => 'assets/img/empresa/'
        ]);
    }

}

laravel/app/Http/Controllers/EmpresaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Models\Empresa;
use App\Models\Certificacao;

class EmpresaController extends Controller
{
    public function index()
    {
        $empresa = Empresa::first();
        $certificacoes = Certificacao::ordenados()->get();

        return view('frontend.empresa', compact('empresa', 'certificacoes'));
    }
}

laravel/app/Http/Controllers/Painel/EmpresaController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\EmpresaRequest;
use App\Http\Controllers\Controller;

use App\Models\Empresa;

class EmpresaController extends Controller
{
    public function index()
    {
        $registro = Empresa::first();

        return view('painel.empresa.edit', compact('registro'));
    }

    public function update(EmpresaRequest $request, Empresa $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Empresa::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.empresa.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/empresa/certificacoes/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Empresa / Certificações /</small> Adicionar Certificação</h2>
    </legend>

    {!! Form::open(['route' => 'painel.empresa.certificacoes.store', 'files' => true]) !!}

        @include('painel.empresa.certificacoes.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/empresa/certificacoes/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Empresa / Certificações /</small> Editar Certificação</h2>
    </legend>

    {!! Form::model($registro, [
        'route'  => ['painel.empresa.certificacoes.update', $registro->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.empresa.certificacoes.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/empresa/certificacoes/form.blade.php
@include('painel.common.flash')

<div class="well form-group">
    {!! Form::label('imagem', 'Imagem') !!}
@if($submitText == 'Alterar')
    <img src="{{ url('assets/img/certificacoes/'.$registro->imagem) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
@endif
    {!! Form::file('imagem', ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('texto', 'Texto') !!}
    {!! Form::text('texto', null, ['class' => 'form-control']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.empresa.certificacoes.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/empresa/certificacoes/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <a href="{{ route('painel.empresa.index') }}" class="btn btn-default btn-sm">
        &larr; Voltar para Empresa
    </a>

    <legend>
        <h2>
            <small>Empresa /</small> Certificações
            <a href="{{ route('painel.empresa.certificacoes.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Certificação</a>
        </h2>
    </legend>

    @if(!count($registros))
    <div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="empresa_certificacoes">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Imagem</th>
                <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)
            <tr class="tr-row" id="{{ $registro->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td><img src="{{ asset('assets/img/certificacoes/'.$registro->imagem) }}" style="width: 100%; max-width:150px;" alt=""></td>
                <td class="crud-actions">
                    {!! Form::open([
                        'route'  => ['painel.empresa.certificacoes.destroy', $registro->id],
                        'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.empresa.certificacoes.edit', $registro->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>


    @endif

@endsection