laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('empresa', 'EmpresaController@index')->name('empresa');

    Route::get('produtos/{produtos_categoria?}', 'ProdutosController@index')->name('produtos');
    Route::get('produtos/{produtos_categoria}/{produto_slug}', 'ProdutosController@show')->name('produtos.show');
    Route::post('adiciona-produto', 'OrcamentoController@adiciona');
    Route::post('exclui-produto', 'OrcamentoController@exclui');
    Route::post('atualiza-produto', 'OrcamentoController@atualiza');

    Route::get('noticias/{noticia_slug?}', 'NoticiasController@index')->name('noticias');
    Route::get('promocoes', 'PromocoesController@index')->name('promocoes');

    Route::get('representantes', 'RepresentantesController@index')->name('representantes');
    Route::post('representantes', 'RepresentantesController@post')->name('representantes.post');

    Route::get('faq', 'FaqController@index')->name('faq');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::get('busca', 'ProdutosController@busca')->name('busca');

    Route::post('orcamento/cadastro', 'OrcamentoController@cadastro')->name('orcamento.cadastro');
    Route::post('orcamento/redefinir', 'Auth\PasswordController@sendResetLinkEmail')->name('orcamento.redefinir');
    Route::get('orcamento/redefinicao/{token}', 'Auth\PasswordController@showResetForm');
    Route::post('orcamento/reset', 'Auth\PasswordController@reset')->name('orcamento.reset');
    Route::post('orcamento/login', 'OrcamentoController@login')->name('orcamento.login');
    Route::get('orcamento/logout', 'OrcamentoController@logout')->name('orcamento.logout');
    Route::get('orcamento', 'OrcamentoController@index')->name('orcamento');

    Route::group(['middleware' => 'authCliente'], function() {
        Route::post('orcamento', 'OrcamentoController@post')->name('orcamento.post');
    });

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth', 'authAdmin']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
        Route::resource('produtos/categorias', 'ProdutosCategoriasController');
        Route::resource('produtos', 'ProdutosController');
        Route::get('produtos/{produtos}/imagens/clear', [
            'as'   => 'painel.produtos.imagens.clear',
            'uses' => 'ProdutosImagensController@clear'
        ]);
        Route::resource('produtos.imagens', 'ProdutosImagensController', ['parameters' => ['imagens' => 'imagens_produtos']]);
        Route::resource('representantes/contatos', 'RepresentantesContatosController');
		Route::resource('representantes', 'RepresentantesController');
		Route::resource('home/chamadas', 'ChamadasController', ['only' => ['index', 'update']]);
		Route::resource('home/banners', 'BannersController');
		Route::resource('empresa/certificacoes', 'EmpresaCertificacoesController');
		Route::resource('empresa', 'EmpresaController', ['only' => ['index', 'update']]);
        Route::resource('noticias', 'NoticiasController');
		Route::resource('faq/imagem', 'FaqImagemController', ['only' => ['index', 'update']]);
		Route::resource('faq', 'FaqController');
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('orcamentos', 'OrcamentosController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Models/Representante.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Helpers\CropImage;

class Representante extends Model
{
    protected $table = 'representantes';

    protected $guarded = ['id'];

    public function scopeOrdenados($query)
    {
        return $query->orderBy('ordem', 'ASC')->orderBy('id', 'DESC');
    }

}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);
            return redirect()->route('painel.home.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $registro->update($input);
            return redirect()->route('painel.home.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.home.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ChamadasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ChamadasRequest;
use App\Http\Controllers\Controller;

use App\Models\Chamadas;

class ChamadasController extends Controller
{
    public function index()
    {
        $registro = Chamadas::first();

        return view('painel.chamadas.edit', compact('registro'));
    }

    public function update(ChamadasRequest $request, Chamadas $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['chamada_1_imagem'])) $input['chamada_1_imagem'] = Chamadas::upload_chamada_1_imagem();
            if (isset($input['chamada_2_imagem'])) $input['chamada_2_imagem'] = Chamadas::upload_chamada_2_imagem();
            if (isset($input['chamada_3_imagem'])) $input['chamada_3_imagem'] = Chamadas::upload_chamada_3_imagem();

            $registro->update($input);

            return redirect()->route('painel.home.chamadas.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('id', 'DESC')->paginate(15);

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/EmpresaCertificacoesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\EmpresaCertificacoesRequest;
use App\Http\Controllers\Controller;

use App\Models\Certificacao;

class EmpresaCertificacoesController extends Controller
{
    public function index()
    {
        $registros = Certificacao::ordenados()->get();

        return view('painel.empresa.certificacoes.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.empresa.certificacoes.create');
    }

    public function store(EmpresaCertificacoesRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Certificacao::upload_imagem();

            Certificacao::create($input);
            return redirect()->route('painel.empresa.certificacoes.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Certificacao $registro)
    {
        return view('painel.empresa.certificacoes.edit', compact('registro'));
    }

    public function update(EmpresaCertificacoesRequest $request, Certificacao $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Certificacao::upload_imagem();

            $registro->update($input);
            return redirect()->route('painel.empresa.certificacoes.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Certificacao $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.empresa.certificacoes.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/EmpresaController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\EmpresaRequest;
use App\Http\Controllers\Controller;

use App\Models\Empresa;

class EmpresaController extends Controller
{
    public function index()
    {
        $registro = Empresa::first();

        return view('painel.empresa.edit', compact('registro'));
    }

    public function update(EmpresaRequest $request, Empresa $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Empresa::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.empresa.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/FaqController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\FaqRequest;
use App\Http\Controllers\Controller;

use App\Models\Pergunta;

class FaqController extends Controller
{
    public function index()
    {
        $registros = Pergunta::ordenados()->get();

        return view('painel.faq.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.faq.create');
    }

    public function store(FaqRequest $request)
    {
        try {

            $input = $request->all();


            Pergunta::create($input);
            return redirect()->route('painel.faq.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Pergunta $registro)
    {
        return view('painel.faq.edit', compact('registro'));
    }

    public function update(FaqRequest $request, Pergunta $registro)
    {
        try {

            $input = $request->all();


            $registro->update($input);
            return redirect()->route('painel.faq.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Pergunta $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.faq.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/FaqImagemController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\FaqImagemRequest;
use App\Http\Controllers\Controller;

use App\Models\FaqImagem;

class FaqImagemController extends Controller
{
    public function index()
    {
        $registro = FaqImagem::first();

        return view('painel.faq.imagem.edit', compact('registro'));
    }

    public function update(FaqImagemRequest $request, FaqImagem $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = FaqImagem::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.faq.imagem.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/NoticiasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\NoticiasRequest;
use App\Http\Controllers\Controller;

use App\Models\Noticia;

class NoticiasController extends Controller
{
    public function index()
    {
        $registros = Noticia::ordenados()->paginate(10);

        return view('painel.noticias.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.noticias.create');
    }

    public function store(NoticiasRequest $request)
    {
        try {

            $input = $request->all();


            Noticia::create($input);
            return redirect()->route('painel.noticias.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Noticia $registro)
    {
        return view('painel.noticias.edit', compact('registro'));
    }

    public function update(NoticiasRequest $request, Noticia $registro)
    {
        try {

            $input = $request->all();


            $registro->update($input);
            return redirect()->route('painel.noticias.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Noticia $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.noticias.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/resources/views/painel/representantes/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Representantes /</small> Adicionar Representante</h2>
    </legend>

    {!! Form::open(['route' => 'painel.representantes.store', 'files' => true]) !!}

        @include('painel.representantes.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/representantes/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Representantes /</small> Editar Representante</h2>
    </legend>

    {!! Form::model($registro, [
        'route'  => ['painel.representantes.update', $registro->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.representantes.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/representantes/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('nome', 'Nome') !!}
    {!! Form::text('nome', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('informacoes', 'Informações') !!}
    {!! Form::textarea('informacoes', null, ['class' => 'form-control ckeditor', 'data-editor' => 'representantes']) !!}
</div>

<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            {!! Form::label('estado', 'Estado') !!}
            {!! Form::select('estado', Tools::listaEstados(), null, ['class' => 'form-control', 'placeholder' => 'Selecione']) !!}
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            {!! Form::label('cidade', 'Cidade') !!}
            {!! Form::text('cidade', null, ['class' => 'form-control']) !!}
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            {!! Form::label('cep', 'CEP') !!}
            {!! Form::text('cep', null, ['class' => 'form-control']) !!}
        </div>
    </div>
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.representantes.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/representantes/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <legend>
        <h2>
            Representantes
            <div class="btn-group pull-right">
                <a href="{{ route('painel.representantes.contatos.index') }}" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-envelope" style="margin-right:10px;"></span>
                    Contatos Recebidos
                    @if($contatosRepresentantesNaoLidos >= 1)
                    <span class="label label-warning" style="margin-left:3px;">{{ $contatosRepresentantesNaoLidos }}</span>
                    @endif
                </a>
                <a href="{{ route('painel.representantes.create') }}" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Representante</a>
            </div>
        </h2>
    </legend>

    @if(!count($registros))
    <div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="representantes">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Estado</th>
                <th>Cidade</th>
                <th>Nome</th>
                <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)
            <tr class="tr-row" id="{{ $registro->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td>{{ $registro->estado }}</td>
                <td>{{ $registro->cidade }}</td>
                <td>{{ $registro->nome }}</td>
                <td class="crud-actions">
                    {!! Form::open([
                        'route'  => ['painel.representantes.destroy', $registro->id],
                        'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.representantes.edit', $registro->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>


    @endif

@endsection